@startuml
  entity User {
    id
    email
    username
    password
  }

  class UserRepository {
    persist(user)
    findAll()
    findById(id)
  }

  class uuid

  class CreateUser
  class ListUsers
  class GetUserById

  class container

  class Graphql {
    Query: ListUsers()
    Query: GetUserById(ID)
    Mutation: CreateUser(UserInput)
  }

  uuid -> UserRepository

  User --> CreateUser
  UserRepository --> CreateUser
  UserRepository --> ListUsers
  UserRepository --> GetUserById

  CreateUser --> container
  ListUsers --> container
  GetUserById --> container

  container -> Graphql

@enduml